### ISSUE TITLE
BadRequestError due to python/tuple in YAML

### ISSUE THREAD

**Issue by albertvillanova** [huggingface/huggingface_hub#1950]
### Describe the bug

I get a `BadRequestError` for dataset https://huggingface.co/datasets/capes, when making push to hub.

Maybe the issue is caused by the underlying service API.

- Note that one of the features of this dataset is the `translation`, with a Python tuple:
```yaml
dataset_info:
  features:
  - name: translation
    dtype:
      translation:
        languages:
        - en
        - pt
```

### Logs

```shell
BadRequestError:  (Request ID: Root=1-659558eb-7c4f530f1c1f560317f09223;85312e92-4e2a-4e94-ba08-2409317d4d45)

Bad request for commit endpoint:
Invalid YAML in README.md: unknown tag !<tag:yaml.org,2002:python/tuple> (33:3)

 30 |         languages: !!python/tuple
 31 |         - en
 32 |         - pt
 33 |   splits:
--------^
 34 |   - name: train
 35 |     num_bytes: 472483436
```
```


### System info

```shell
- huggingface_hub version: 0.21.0.dev0
- Platform: Linux-5.15.0-91-generic-x86_64-with-glibc2.31
- Python version: 3.9.7
```
