### ISSUE TITLE
[Feature Request] Support COEP/COOP headers on Spaces running via Docker SDK

### ISSUE THREAD

**Issue by felladrin** [huggingface/huggingface_hub#2127]
I see COEP/COOP headers are supported on HuggingFace Spaces [[1](https://github.com/huggingface/huggingface_hub/issues/1525)] for static SDK [[2](https://huggingface.co/spaces/radames/OpenAI-CLIP-JavaScript)], by adding the following in the README.md:
```yml
custom_headers:
  cross-origin-embedder-policy: require-corp
  cross-origin-opener-policy: same-origin
  cross-origin-resource-policy: cross-origin
```

But when I added these lines to [this space](https://huggingface.co/spaces/Felladrin/MiniSearch), the space wasn't loading anymore via `https://huggingface.co/spaces/Felladrin/MiniSearch`.  
It did load perfectly fine when using `https://felladrin-minisearch.hf.space/`, though.  
But even so, when loaded via the latter URL, the space was not loaded with cross origin isolation.

I think this is because the space uses Docker SDK (`sdk: docker` in the readme).  
[To reproduce this issue, you can clone the space and add the `custom_headers` to the `README.md`.]
If that's the case, are there plans to support COEP/COOP headers on Spaces running via Docker SDK?

**Comment by Wauplin** [comment]
Friendly pinging @xenova  @julien-c @radames who discussed/worked on this feature back then

**Comment by radames** [comment]
hi @felladrin 
Yes, the `custom_headers:` on HF enables the headers on the parent origin `huggingface.co`. Since your Space is a Docker Space, you also have to ensure that the headers are provided. The COEP/COOP policy is quite restrictive; thus, if we're embedding Apps under our origin, all sub-resources must also follow and provide the headers. My PR adds the header to your Express server. I've tested it on a duplicated space, and it works. Don't forget to add back the metadata to your `README.md` on HF.

```
custom_headers:
  cross-origin-embedder-policy: require-corp
  cross-origin-opener-policy: same-origin
  cross-origin-resource-policy: cross-origin
```

I sent you a PR on your GH project since I've noticed you're syncing it with your HF Space
https://github.com/felladrin/MiniSearch/pull/237
