### ISSUE TITLE
Huggingface_hub import fails with partially initialized module when EAGER_IMPORT=true

### ISSUE THREAD

**Issue by GeorgWa** [huggingface/huggingface_hub#2206]
### Describe the bug

One of our pyinstaller workflow currently fails on the `transformers` and `huggingface_hub` packages as it can't import the huggingface_hub module during pyinstaller discovery. For the pyinstaller build we deactivate `huggingface_hub` lazy loading by setting `EAGER_IMPORT=true`.
https://github.com/pyinstaller/pyinstaller-hooks-contrib/issues/721

I've reduced the case as much as possible and it already appears by just installing `huggingface_hub` and caling the line from transformers `from huggingface_hub import get_full_repo_name; print("success")`:

```
conda create -n testenv python==3.11
conda activate testenv
export EAGER_IMPORT="true"
pip install --upgrade huggingface_hub
python -c 'from huggingface_hub import get_full_repo_name; print("success")'
```

### Reproduction

```
on:
  push

name: Test Huggingface

jobs:
  test:
    strategy:
      matrix:
        os: [macos-latest-xlarge, ubuntu-latest, windows-latest, macos-latest]

    env:
        ARCH: x64
        EAGER_IMPORT: true
    runs-on: ${{ matrix.os }}
    steps:
    - name: Install conda
      uses: conda-incubator/setup-miniconda@v3
      with:
        miniconda-version: "latest"
        continue-on-error: true
        auto-update-conda: true
        activate-environment: alpha
        python-version: "3.11"
    
    - name: Test Huggingface
      shell: bash -el {0}
      run: |
        pip install --upgrade huggingface_hub
        python -c 'from huggingface_hub import get_full_repo_name; print("success")'
```

### Logs

```shell
`
pip install --upgrade huggingface_hub
  python -c 'from huggingface_hub import get_full_repo_name; print("success")'
  shell: /bin/bash -el {0}
  env:
    ARCH: x64
    EAGER_IMPORT: true
    INPUT_RUN_POST: true
    CONDA: /Users/runner/miniconda3
    CONDA_PKGS_DIR: /Users/runner/conda_pkgs_dir
Collecting huggingface_hub
  Downloading huggingface_hub-0.22.2-py3-none-any.whl.metadata (12 kB)
Collecting filelock (from huggingface_hub)
  Downloading filelock-3.13.3-py3-none-any.whl.metadata (2.8 kB)
Collecting fsspec>=2023.5.0 (from huggingface_hub)
  Downloading fsspec-2024.3.1-py3-none-any.whl.metadata (6.8 kB)
Collecting packaging>=20.9 (from huggingface_hub)
  Downloading packaging-24.0-py3-none-any.whl.metadata (3.2 kB)
Collecting pyyaml>=5.1 (from huggingface_hub)
  Downloading PyYAML-6.0.1-cp311-cp311-macosx_11_0_arm64.whl.metadata (2.1 kB)
Collecting requests (from huggingface_hub)
  Downloading requests-2.31.0-py3-none-any.whl.metadata (4.6 kB)
Collecting tqdm>=4.42.1 (from huggingface_hub)
  Downloading tqdm-4.66.2-py3-none-any.whl.metadata (57 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 57.6/57.6 kB 3.1 MB/s eta 0:00:00
Collecting typing-extensions>=3.7.4.3 (from huggingface_hub)
  Downloading typing_extensions-4.11.0-py3-none-any.whl.metadata (3.0 kB)
Collecting charset-normalizer<4,>=2 (from requests->huggingface_hub)
  Downloading charset_normalizer-3.3.2-cp311-cp311-macosx_11_0_arm64.whl.metadata (33 kB)
Collecting idna<4,>=2.5 (from requests->huggingface_hub)
  Downloading idna-3.6-py3-none-any.whl.metadata (9.9 kB)
Collecting urllib3<3,>=1.21.1 (from requests->huggingface_hub)
  Downloading urllib3-2.2.1-py3-none-any.whl.metadata (6.4 kB)
Collecting certifi>=2017.4.17 (from requests->huggingface_hub)
  Using cached certifi-2024.2.2-py3-none-any.whl.metadata (2.2 kB)
Downloading huggingface_hub-0.22.2-py3-none-any.whl (388 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 388.9/388.9 kB 16.0 MB/s eta 0:00:00
Downloading fsspec-2024.3.1-py3-none-any.whl (171 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 172.0/172.0 kB 30.9 MB/s eta 0:00:00
Downloading packaging-24.0-py3-none-any.whl (53 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 53.5/53.5 kB 12.1 MB/s eta 0:00:00
Downloading PyYAML-6.0.1-cp311-cp311-macosx_11_0_arm64.whl (167 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 167.5/167.5 kB 33.0 MB/s eta 0:00:00
Downloading tqdm-4.66.2-py3-none-any.whl (78 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 78.3/78.3 kB 19.4 MB/s eta 0:00:00
Downloading typing_extensions-4.11.0-py3-none-any.whl (34 kB)
Downloading filelock-3.13.3-py3-none-any.whl (11 kB)
Downloading requests-2.31.0-py3-none-any.whl (62 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 62.6/62.6 kB 14.2 MB/s eta 0:00:00
Using cached certifi-2024.2.2-py3-none-any.whl (163 kB)
Downloading charset_normalizer-3.3.2-cp311-cp311-macosx_11_0_arm64.whl (118 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 119.0/119.0 kB 27.3 MB/s eta 0:00:00
Downloading idna-3.6-py3-none-any.whl (61 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 61.6/61.6 kB 14.0 MB/s eta 0:00:00
Downloading urllib3-2.2.1-py3-none-any.whl (121 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 121.1/121.1 kB 29.4 MB/s eta 0:00:00
Installing collected packages: urllib3, typing-extensions, tqdm, pyyaml, packaging, idna, fsspec, filelock, charset-normalizer, certifi, requests, huggingface_hub
Successfully installed certifi-2024.2.2 charset-normalizer-3.3.2 filelock-3.13.3 fsspec-2024.3.1 huggingface_hub-0.22.2 idna-3.6 packaging-24.0 pyyaml-6.0.1 requests-2.31.0 tqdm-4.66.2 typing-extensions-4.11.0 urllib3-2.2.1
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/runner/miniconda3/envs/alpha/lib/python3.11/site-packages/huggingface_hub/__init__.py", line 511, in <module>
    __getattr__, __dir__, __all__ = _attach(__name__, submodules=[], submod_attrs=_SUBMOD_ATTRS)
                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/runner/miniconda3/envs/alpha/lib/python3.11/site-packages/huggingface_hub/__init__.py", line 506, in _attach
    __getattr__(attr)
  File "/Users/runner/miniconda3/envs/alpha/lib/python3.11/site-packages/huggingface_hub/__init__.py", line 487, in __getattr__
    submod = importlib.import_module(submod_path)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/runner/miniconda3/envs/alpha/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/runner/miniconda3/envs/alpha/lib/python3.11/site-packages/huggingface_hub/hf_api.py", line 50, in <module>
    from ._commit_api import (
  File "/Users/runner/miniconda3/envs/alpha/lib/python3.11/site-packages/huggingface_hub/_commit_api.py", line 18, in <module>
    from huggingface_hub import get_session
ImportError: cannot import name 'get_session' from partially initialized module 'huggingface_hub' (most likely due to a circular import) (/Users/runner/miniconda3/envs/alpha/lib/python3.11/site-packages/huggingface_hub/__init__.py)
Error: Process completed with exit code 1.
`
```

### System info

```shell
N/A
```
